#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cp -u interfaceProperties.? cssInterDyMFoam
cp -u interfaceProperties.? cssInterFallFoam
cp -u *TwoFluid* cssInterDyMFoam
cp -u *TwoFluid* cssInterFallFoam

wmake
wmake cssInterDyMFoam
wmake cssInterFallFoam

# ----------------------------------------------------------------- end-of-file
