#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean
wclean cssInterDyMFoam
wclean cssInterFallFoam

# ----------------------------------------------------------------- end-of-file
